apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: tms-doknotstatus-converter
  namespace: min-side
  labels:
    team: min-side
spec:
  envFrom:
    - secret: tms-doknotstatus-converter-secrets
  image: {{version}}
  port: 8080
  liveness:
    path: /isAlive
  readiness:
    path: /isReady
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      cpu: "1"
      memory: 768Mi
    requests:
      cpu: "20m"
      memory: 64Mi
  kafka:
    pool: nav-prod
